#ifndef MEMORIES_PC_GUEST_IMAGE_H
#define MEMORIES_PC_GUEST_IMAGE_H
/* ILP32 bring-up memory model: the 2 MiB of PS1 RAM is mapped at its real
 * KSEG0 address, so game globals linked at their retail addresses, pointers
 * stored in game data and 32-bit structure layouts all hold unchanged. The
 * same pages are visible at KSEG1 and at the physical address (from 0x10000;
 * hosts reserve the first 64 KiB), which is what 24-bit packet links use.
 * The scratchpad is a separate 4 KiB mapping at 0x1F800000. */
#include <stddef.h>

#define MEMORIES_GUEST_RAM 0x80000000u
#define MEMORIES_GUEST_RAM_SIZE 0x200000u

/* Both return 0 on success and print the reason on failure. */
int Memories_GuestMap(void);
/* Copy a user-supplied PS-X EXE's initialized image to its load address.
 * MIPS text comes along unused; it keeps every data offset exact. */
int Memories_GuestLoadExe(const char *path);
/* The same, from an executable already in memory (read off the disc image:
 * platform/game_files.h). `name` is for messages. */
int Memories_GuestLoadExeData(const unsigned char *data, size_t size, const char *name);
/* Generated by tools/pc/build_game32.py: every linked function that has a
 * retail address, sorted by that address. */
typedef struct MemoriesGuestFunction {
    unsigned guest;
    void (*host)(void);
    unsigned bank, identifier; /* shared load bank: valid while *bank == identifier; 0 = always */
} MemoriesGuestFunction;
extern const MemoriesGuestFunction Memories_FunctionMap[];
extern const unsigned Memories_FunctionMapCount;

/* Generated likewise: the modules built for a shared load bank, with the host
 * sections holding their variables. See src/pc/guest/modules.c. */
typedef struct MemoriesModule {
    const char *name;
    unsigned bank, identifier;
    char *data, *data_end, *bss, *bss_end;
} MemoriesModule;
extern const MemoriesModule Memories_Modules[];
extern const unsigned Memories_ModuleCount;
#include <stddef.h>
int Memories_ModulesInit(void);
int Memories_ModuleIsResident(unsigned bank, unsigned identifier);
/* Tell the registry that the loader stored into guest memory. */
void Memories_GuestWritten(void *destination, size_t length);

/* Where an indirect call or jump into guest memory goes (branch_thunks.c):
 * the native function of that address, the MIPS interpreter's entry, or the
 * address itself outside guest memory. Set by Memories_GuestMap; while it is
 * NULL every target is taken as it is. */
extern void *(*Memories_GuestBranchResolver)(unsigned address);

/* Reached by a generated stub for a routine with no native implementation. */
void Memories_Unimplemented(const char *name);
#endif
